import type { HistoricalCampaignPreset } from '../../types/campaign';

export const HISTORICAL_CAMPAIGNS: HistoricalCampaignPreset[] = [
  {
    id: 'campaign_imf_crisis',
    titleKo: 'IMF 외환위기 생존전',
    subtitleKo: '원화 급락과 고금리 속 글로벌 분산투자의 힘',
    periodKo: '1995년 말 ~ 2005년 말 (10개년)',
    startYear: 1995,
    endYear: 2005,
    initialCashKRW: 10000000,
    annualContributionKRW: 3000000,
    learningGoalKo: '외환위기 폭락과 달러 환율 효과, 1999년 V자 반등을 경험하며 통화 분산과 안전마진의 중요성을 체득합니다.',
    recommendedPlayMinutes: 15,
    keyObservationVariablesKo: ['원/달러 환율 (800원 -> 2,000원 -> 1,000원)', '한국 CD 금리 (연 25% 초고금리)', '반도체·제조업 구조조정'],
    historicalDescriptionKo: '1997년 외환보유액 고갈로 닥친 사상 초유의 국가 부도 위기. 미국 달러 자산의 환율 방어 효과와 V자 반등 국면의 우량주 턴어라운드를 검증합니다.',
    badgeKo: '위기 극복',
  },
  {
    id: 'campaign_dotcom_bubble',
    titleKo: '닷컴 버블 투자 실험',
    subtitleKo: '실체 없는 테마 열풍과 펀더멘털의 괴리',
    periodKo: '1995년 말 ~ 2005년 말 (10개년)',
    startYear: 1995,
    endYear: 2005,
    initialCashKRW: 10000000,
    annualContributionKRW: 3000000,
    learningGoalKo: '인터넷 혁명 초기의 주가 폭등과 버블 붕괴 과정을 통과하며 밸류에이션 원칙과 분산투자의 중요성을 배웁니다.',
    recommendedPlayMinutes: 15,
    keyObservationVariablesKo: ['나스닥/코스닥 지수 밸류에이션(PER)', '인터넷/IT 기업 신규 상장 열풍', '연준 기준금리 인상'],
    historicalDescriptionKo: '닷컴 기업 주가가 수십 배 폭등하던 1999년의 광풍과 2000년 봄 이후 닥친 80% 폭락의 잔혹한 교훈을 체험합니다.',
    badgeKo: '버블 검증',
  },
  {
    id: 'campaign_gfc_rebalance',
    titleKo: '글로벌 금융위기 리밸런싱',
    subtitleKo: '대공황 이래 최대 금융 충격과 양적완화(QE)',
    periodKo: '2005년 말 ~ 2015년 말 (10개년)',
    startYear: 2005,
    endYear: 2015,
    initialCashKRW: 20000000,
    annualContributionKRW: 5000000,
    learningGoalKo: '2008년 리먼 브라더스 파산의 공포 속에서 정계량 리밸런싱 규칙을 지켜냈을 때의 장기 복리 회복력을 증명합니다.',
    recommendedPlayMinutes: 15,
    keyObservationVariablesKo: ['미국 주택가격지수 및 서브프라임 연체율', 'VIX 변동성 지수 및 신용 스프레드', '연준 양적완화(QE) 및 제로금리'],
    historicalDescriptionKo: '코스피 2,000 돌파의 환호에서 2008년 반토막 폭락으로 이어진 대위기. 최저점에서 패닉셀하지 않고 분할매수한 자산배분의 위력을 확인합니다.',
    badgeKo: '원칙 수호',
  },
  {
    id: 'campaign_pandemic_ai',
    titleKo: '팬데믹과 AI 혁명',
    subtitleKo: '초유의 경제 셧다운, 인플레이션과 생성형 AI',
    periodKo: '2015년 말 ~ 2025년 말 (10개년)',
    startYear: 2015,
    endYear: 2025,
    initialCashKRW: 30000000,
    annualContributionKRW: 10000000,
    learningGoalKo: '2020년 3월 코로나19 폭락, 제로금리 유동성 파티, 2022년 고금리 충격, 2023년 ChatGPT AI 혁명까지 현대 금융시장의 격변을 관통합니다.',
    recommendedPlayMinutes: 15,
    keyObservationVariablesKo: ['팬데믹 봉쇄 지수 및 언택트 수요', '미국 CPI 인플레이션 (최고 9.1%)', '연준 초고속 긴축 (0% -> 5.5%)', '생성형 AI 빅테크 Capex'],
    historicalDescriptionKo: '가장 최근의 10년을 직접 경험하며 초저금리와 초고금리, AI 주도주 랠리 속에서 나만의 원칙을 수립합니다.',
    badgeKo: '현대 시장',
  },
];
