import type { AchievementDefinition } from '../../types/achievement';

export const PROCESS_ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'first_evidence_trade',
    nameKo: '근거 있는 첫 투자',
    category: 'EVIDENCE',
    descriptionKo: '뉴스 또는 공시를 직접 연결하여 첫 거래를 실행했습니다.',
    requirementKo: '주문 시 뉴스 또는 투자 가설(Thesis) 1건 이상 연결',
    iconName: 'FileText',
    maxProgress: 1,
  },
  {
    id: 'filing_detective',
    nameKo: '공시 탐정',
    category: 'RESEARCH',
    descriptionKo: '기업의 공식 공시 및 IR 자료를 10건 이상 확인하고 분석했습니다.',
    requirementKo: '공식 공시 10건 이상 조회',
    iconName: 'Search',
    maxProgress: 10,
  },
  {
    id: 'five_year_discipline',
    nameKo: '5년 원칙 수호자',
    category: 'DISCIPLINE',
    descriptionKo: '5년간 사전에 정한 투자 규칙과 자산배분 원칙을 꾸준히 유지했습니다.',
    requirementKo: '5년 연속 리밸런싱 및 자산배분 규칙 유지',
    iconName: 'Shield',
    maxProgress: 5,
  },
  {
    id: 'diversification_designer',
    nameKo: '분산투자 설계자',
    category: 'DIVERSIFICATION',
    descriptionKo: '5개 이상의 개별 종목과 3개 이상의 다양한 업종에 분산 투자했습니다.',
    requirementKo: '동시 보유 종목 5개 이상 & 3개 업종 이상 분산',
    iconName: 'Layers',
    maxProgress: 5,
  },
  {
    id: 'concentration_manager',
    nameKo: '집중위험 관리자',
    category: 'RISK_MGMT',
    descriptionKo: '단일 종목 비중을 35% 이하로 엄격하게 관리하여 포트폴리오 쏠림을 방어했습니다.',
    requirementKo: '전체 보유 종목 중 단일 종목 비중 35% 이하 유지',
    iconName: 'PieChart',
    maxProgress: 1,
  },
  {
    id: 'cost_saver',
    nameKo: '비용 절약가',
    category: 'COST_SAVING',
    descriptionKo: '불필요한 과잉 매매를 자제하여 총 자산 대비 거래비용을 0.5% 이하로 관리했습니다.',
    requirementKo: '누적 거래 수수료를 총자산 대비 0.5% 이하로 유지',
    iconName: 'DollarSign',
    maxProgress: 1,
  },
  {
    id: 'crisis_survivor',
    nameKo: '위기 속 원칙 수호자',
    category: 'DISCIPLINE',
    descriptionKo: '시장 급락기(-15% 이상 하락)에도 뇌동매매 투매 없이 침착하게 원칙을 지켰습니다.',
    requirementKo: '시장 위기 연도에 사전 리밸런싱 규칙 유지',
    iconName: 'Anchor',
    maxProgress: 1,
  },
  {
    id: 'fx_analyst',
    nameKo: '환율 분석가',
    category: 'RESEARCH',
    descriptionKo: '미국 주식 투자 근거에 환율 변동 요인과 글로벌 매크로를 메모로 기록했습니다.',
    requirementKo: '미국주식 거래 메모에 환율/통화 관련 가설 작성',
    iconName: 'Globe',
    maxProgress: 1,
  },
  {
    id: 'contrary_evidence',
    nameKo: '반대 근거 수집가',
    category: 'EVIDENCE',
    descriptionKo: '투자 결정 전 긍정적 측면뿐만 아니라 부정적 리스크와 한계 요인을 함께 검토했습니다.',
    requirementKo: '중립적 뉴스 분석의 부정적 해석 및 한계 3회 이상 확인',
    iconName: 'Scale',
    maxProgress: 3,
  },
  {
    id: 'benchmark_reviewer',
    nameKo: '지수 비교자',
    category: 'RESEARCH',
    descriptionKo: '코스피, S&P 500, 한·미 50:50 세 가지 벤치마크 성과를 모두 꼼꼼히 비교 검토했습니다.',
    requirementKo: '3대 벤치마크 성과 비교 탭 전체 확인',
    iconName: 'BarChart2',
    maxProgress: 1,
  },
];
