#!/usr/bin/env python3
"""
scripts/add_expanded_company_news.py
Adds historically accurate news articles for the 10 new expanded companies
"""

import json
import os

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NEWS_FILE = os.path.join(ROOT_DIR, "src", "data", "news", "historical_news_all.json")
BACKUP_NEWS_FILE = os.path.join(ROOT_DIR, "data", "news", "historical_news_all.json")

RAW_JSON_ARTICLES = """
[
  {
    "id": "COMP_1989_KR_001600",
    "scope": "COMPANY",
    "market": "KR",
    "canonicalCompanyIds": ["KR_001600"],
    "relatedTickers": ["001600"],
    "relatedSectors": ["철강 / 소재"],
    "eventDate": "1989-11-20",
    "publishedAt": "1989-11-20",
    "availableFrom": "1989-11-20",
    "datePrecision": "DAY",
    "originalTitle": "한보철강공업 증권거래소 상장 및 당진제철소 건설 추진",
    "titleKo": "한보철강공업 주권 신규 상장… 당진 코렉스 제철소 대규모 투자",
    "summaryKo": "한보그룹 주력사인 한보철강공업이 증권거래소에 상장되었습니다. 회사는 당진에 연산 수백만 톤 규모의 코렉스(COREX) 공법 제철소 건설을 본격 추진한다고 발표했습니다.",
    "sourceName": "매일경제 / 한국거래소",
    "sourceUrl": "https://kind.krx.co.kr",
    "sourceType": "NEWS_AGENCY",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["상장", "철강", "설비투자"],
    "affectedChannels": ["CAPEX", "DEBT"],
    "neutralAnalysis": {
      "verifiedFacts": "한보철강공업 1989년 11월 20일 증권거래소 신규 상장, 공모가 16,000원.",
      "impactChannels": ["CAPEX", "DEBT"],
      "positiveInterpretation": "신공법 제철소 완공 시 국내 2위 일관제철소 도약 기대.",
      "negativeInterpretation": "자본 규모 대비 막대한 차입금 조달로 재무 건전성 악화 우려.",
      "unknownAtTheTime": "당진제철소 건설 비용이 5조 원 이상으로 눈덩이처럼 불어날지 여부."
    },
    "importanceScore": 8,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_1996_KR_001600",
    "scope": "COMPANY",
    "market": "KR",
    "canonicalCompanyIds": ["KR_001600"],
    "relatedTickers": ["001600"],
    "relatedSectors": ["철강 / 소재"],
    "eventDate": "1996-09-15",
    "publishedAt": "1996-09-15",
    "availableFrom": "1996-09-15",
    "datePrecision": "DAY",
    "originalTitle": "한보철강, 당진제철소 투자비 5조원 돌파… 금융권 여신 리스크 우려",
    "titleKo": "한보철강 차입금 5조원 돌파… 은행권 대출 건전성 경고",
    "summaryKo": "한보철강의 당진제철소 투자비가 눈덩이처럼 불어나며 제일은행 등 금융권 대출액이 5조 원을 넘어섰습니다. 철강 시황 악화와 막대한 금융비용으로 유동성 위기설이 제기되고 있습니다.",
    "sourceName": "한국경제신문",
    "sourceUrl": "https://www.hankyung.com",
    "sourceType": "NEWS_AGENCY",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["유동성", "차입금", "리스크"],
    "affectedChannels": ["DEBT", "PROFITABILITY"],
    "neutralAnalysis": {
      "verifiedFacts": "한보철강 부채비율 1,000% 초과, 시중은행 여신 5조 원 이상 집중.",
      "impactChannels": ["DEBT", "PROFITABILITY"],
      "positiveInterpretation": "코렉스 공법 설비 가동 시 현금흐름 개선 가능성 주장.",
      "negativeInterpretation": "연간 영업이익으로 이자비용조차 감당 불가능한 한계기업 상태 도달.",
      "unknownAtTheTime": "정부와 은행권이 언제까지 부실 대출을 연장해 줄 수 있을지 여부."
    },
    "importanceScore": 9,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_1997_KR_001600",
    "scope": "COMPANY",
    "market": "KR",
    "canonicalCompanyIds": ["KR_001600", "KR_000010"],
    "relatedTickers": ["001600", "000010"],
    "relatedSectors": ["철강 / 소재", "금융 / 은행"],
    "eventDate": "1997-01-23",
    "publishedAt": "1997-01-23",
    "availableFrom": "1997-01-23",
    "datePrecision": "DAY",
    "originalTitle": "한보철강 최종 부도 처리… 한보사태 정관계 파문 및 금융권 연쇄 충격",
    "titleKo": "[특보] 한보철강 최종 부도… '한보사태'로 금융시장 패닉",
    "summaryKo": "총 부채 5조 7천억 원에 달하는 한보철강이 조흥·제일은행 등의 어음을 결제하지 못해 최종 부도 처리되었습니다. 주채권은행들의 건전성이 급격히 악화되며 금융시장 전체가 요동치고 있습니다.",
    "sourceName": "조선일보 / 동아일보",
    "sourceUrl": "https://www.chosun.com",
    "sourceType": "NEWS_AGENCY",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["부도", "외환위기", "금융사고"],
    "affectedChannels": ["BANKRUPTCY", "CREDIT_CRUNCH"],
    "neutralAnalysis": {
      "verifiedFacts": "1997년 1월 23일 한보철강 1차 부도 후 최종 부도 확정, 정태수 총괄회장 구속.",
      "impactChannels": ["BANKRUPTCY", "CREDIT_CRUNCH"],
      "positiveInterpretation": "없음.",
      "negativeInterpretation": "주가 90% 이상 폭락, 채권은행 대규모 대손충당금 발생 및 국가신용도 추락.",
      "unknownAtTheTime": "이 부도가 기아·삼미·대우로 이어지며 11월 IMF 외환위기로 직결될지 여부."
    },
    "importanceScore": 10,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_1988_KR_000010",
    "scope": "COMPANY",
    "market": "KR",
    "canonicalCompanyIds": ["KR_000010"],
    "relatedTickers": ["000010"],
    "relatedSectors": ["금융 / 은행"],
    "eventDate": "1988-12-10",
    "publishedAt": "1988-12-10",
    "availableFrom": "1988-12-10",
    "datePrecision": "DAY",
    "originalTitle": "증시 트로이카 열풍 속에 제일은행 주가 연일 신고가 경신",
    "titleKo": "트로이카 금융주 주도… 제일은행 1만 3천원 돌파",
    "summaryKo": "서울올림픽 이후 자본시장 팽창과 통화량 증가로 금융·무역·건설 '트로이카' 주식이 폭등하는 가운데, 시중 5대 은행 중 제일은행이 영업 실적 호조로 신고가를 경신했습니다.",
    "sourceName": "매일경제",
    "sourceUrl": "https://www.mk.co.kr",
    "sourceType": "NEWS_AGENCY",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["금융주", "트로이카", "주가상승"],
    "affectedChannels": ["EARNINGS", "VALUATION"],
    "neutralAnalysis": {
      "verifiedFacts": "1988년 연말 코스피 900선 돌파, 은행주 주가수익비율 급등.",
      "impactChannels": ["EARNINGS", "VALUATION"],
      "positiveInterpretation": "금융 자율화 및 예대마진 확대로 은행권 이익 급증.",
      "negativeInterpretation": "과도한 시중 유동성 유입에 따른 단기 과열 리스크.",
      "unknownAtTheTime": "대기업 여신 편중이 10년 후 외환위기 부실채권으로 돌아올지 여부."
    },
    "importanceScore": 7,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_1997_KR_000010",
    "scope": "COMPANY",
    "market": "KR",
    "canonicalCompanyIds": ["KR_000010"],
    "relatedTickers": ["000010"],
    "relatedSectors": ["금융 / 은행"],
    "eventDate": "1997-12-10",
    "publishedAt": "1997-12-10",
    "availableFrom": "1997-12-10",
    "datePrecision": "DAY",
    "originalTitle": "정부, 제일은행·서울은행에 1조원 출자… 공적자금 투입 긴급 회생",
    "titleKo": "정부, 부실 제일은행에 공적자금 긴급 투입… 감자 추진",
    "summaryKo": "한보철강, 기아그룹, 삼미그룹 등의 연쇄 부도로 제일은행의 부실채권이 감당할 수 없는 수준에 이르자, 정부가 한국은행과 함께 1조 원의 공적자금을 출자하기로 결정했습니다.",
    "sourceName": "한국은행 / 재정경제원",
    "sourceUrl": "https://www.bok.or.kr",
    "sourceType": "GOVERNMENT",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["공적자금", "구조조정", "감자"],
    "affectedChannels": ["CAPITAL_EROSION", "GOVERNMENT_BAILOUT"],
    "neutralAnalysis": {
      "verifiedFacts": "제일은행 BIS 자기자본비율 1% 미만으로 하락, 정부 지분 90% 이상 인수.",
      "impactChannels": ["CAPITAL_EROSION", "GOVERNMENT_BAILOUT"],
      "positiveInterpretation": "은행 파산으로 인한 금융시스템 붕괴 방지.",
      "negativeInterpretation": "기존 주주 주식 대규모 무상감자로 주주 가치 사실상 소멸.",
      "unknownAtTheTime": "외국계 사모펀드(뉴브리지)에 헐값 매각 논란 발생 여부."
    },
    "importanceScore": 9,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_1993_KR_001300",
    "scope": "COMPANY",
    "market": "KR",
    "canonicalCompanyIds": ["KR_001300"],
    "relatedTickers": ["001300"],
    "relatedSectors": ["종합상사 / 무역"],
    "eventDate": "1993-04-15",
    "publishedAt": "1993-04-15",
    "availableFrom": "1993-04-15",
    "datePrecision": "DAY",
    "originalTitle": "대우그룹 김우중 회장 '세계경영' 선포… 동유럽·신흥국 공략 가속",
    "titleKo": "대우 김우중 회장 '세계경영' 선포… 폴란드·우즈벡 등 해외 진출",
    "summaryKo": "(주)대우를 필두로 대우그룹이 '세계경영'을 선포하고 동유럽, 중앙아시아, 중남미 등 신흥국에 자동차, 전자, 무역 현지법인을 잇달아 설립하며 공격적인 글로벌 확장에 나섰습니다.",
    "sourceName": "매일경제 / 한국경제",
    "sourceUrl": "https://www.mk.co.kr",
    "sourceType": "NEWS_AGENCY",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["세계경영", "해외진출", "종합상사"],
    "affectedChannels": ["GLOBAL_EXPANSION", "REVENUE_GROWTH"],
    "neutralAnalysis": {
      "verifiedFacts": "대우그룹 해외 300여 개 법인망 구축, 수출 100억 달러 돌파.",
      "impactChannels": ["GLOBAL_EXPANSION", "REVENUE_GROWTH"],
      "positiveInterpretation": "미개척 신흥시장에서의 선점 효과 및 한국 수출 드라이브 주도.",
      "negativeInterpretation": "해외 차입금과 무리한 인수합병으로 잠재 부실 누적.",
      "unknownAtTheTime": "외환위기 환율 폭등 시 해외 부채가 그룹 전체를 침몰시킬지 여부."
    },
    "importanceScore": 8,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_1999_KR_001300",
    "scope": "COMPANY",
    "market": "KR",
    "canonicalCompanyIds": ["KR_001300"],
    "relatedTickers": ["001300"],
    "relatedSectors": ["종합상사 / 무역"],
    "eventDate": "1999-08-26",
    "publishedAt": "1999-08-26",
    "availableFrom": "1999-08-26",
    "datePrecision": "DAY",
    "originalTitle": "정부 및 채권단, 대우그룹 12개 계열사 전격 워크아웃 결정",
    "titleKo": "[특보] 대우그룹 12개사 워크아웃… 재계 2위 '대마불사' 붕괴",
    "summaryKo": "부채 총액 89조 원에 달하는 재계 2위 대우그룹의 (주)대우, 대우자동차 등 12개 핵심 계열사에 대해 채권단이 워크아웃(기업개선작업)을 공식 결정했습니다. 대마불사의 신화가 종말을 고했습니다.",
    "sourceName": "금융감독위원회 / 채권단",
    "sourceUrl": "https://www.fsc.go.kr",
    "sourceType": "GOVERNMENT",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["워크아웃", "대우사태", "구조조정"],
    "affectedChannels": ["BANKRUPTCY", "DEBT_RESTRUCTURING"],
    "neutralAnalysis": {
      "verifiedFacts": "1999년 8월 26일 대우그룹 12개사 워크아웃 합의, 김우중 회장 경영권 포기.",
      "impactChannels": ["BANKRUPTCY", "DEBT_RESTRUCTURING"],
      "positiveInterpretation": "없음.",
      "negativeInterpretation": "대우 협력업체 연쇄 타격 및 투신권 수익증권 환매 대란(대우채 사태).",
      "unknownAtTheTime": "40조 원대 사상 최대 분식회계 사실이 수사로 밝혀질지 여부."
    },
    "importanceScore": 10,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_2004_KR_025930",
    "scope": "COMPANY",
    "market": "KR",
    "canonicalCompanyIds": ["KR_025930"],
    "relatedTickers": ["025930"],
    "relatedSectors": ["IT / 스마트폰"],
    "eventDate": "2004-11-05",
    "publishedAt": "2004-11-05",
    "availableFrom": "2004-11-05",
    "datePrecision": "DAY",
    "originalTitle": "팬택, SKY 브랜드 앞세워 국내 휴대폰 시장 2위 등극",
    "titleKo": "팬택계열, 'SKY' 돌풍으로 LG전자 제치고 국내 2위 도약",
    "summaryKo": "벤처기업 출신 팬택이 현대큐리텔과 SK텔레텍을 잇달아 인수하며 'SKY' 브랜드로 세련된 디자인의 슬라이드폰을 연이어 히트시켜 국내 휴대폰 시장 2위(점유율 17%)에 올라섰습니다.",
    "sourceName": "전자신문 / 디지털타임스",
    "sourceUrl": "https://www.etnews.com",
    "sourceType": "NEWS_AGENCY",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["스마트폰", "휴대폰", "벤처신화"],
    "affectedChannels": ["MARKET_SHARE", "REVENUE_GROWTH"],
    "neutralAnalysis": {
      "verifiedFacts": "팬택계열 2004년 연간 매출 3조 원 돌파, 글로벌 출하량 2,000만 대 달성.",
      "impactChannels": ["MARKET_SHARE", "REVENUE_GROWTH"],
      "positiveInterpretation": "혁신적 디자인과 마케팅으로 대기업 삼성·LG와 대등한 경쟁.",
      "negativeInterpretation": "인수합병 과정에서 발생한 금융권 차입금 부담 증가.",
      "unknownAtTheTime": "스마트폰 시대로 전환될 때 자체 OS 및 소프트웨어 역량 부재 위험."
    },
    "importanceScore": 8,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_2014_KR_025930",
    "scope": "COMPANY",
    "market": "KR",
    "canonicalCompanyIds": ["KR_025930"],
    "relatedTickers": ["025930"],
    "relatedSectors": ["IT / 스마트폰"],
    "eventDate": "2014-08-19",
    "publishedAt": "2014-08-19",
    "availableFrom": "2014-08-19",
    "datePrecision": "DAY",
    "originalTitle": "팬택, 법정관리(기업회생절차) 신청… 벤처 신화의 몰락",
    "titleKo": "팬택, 법정관리 전격 신청… 스마트폰 전쟁 속 자금난 한계",
    "summaryKo": "베가(Vega) 스마트폰 시리즈의 판매 부진과 이동통신사 영업정지 여파로 자금난을 겪던 팬택이 결국 서울중앙지방법원에 기업회생절차(법정관리)를 신청했습니다.",
    "sourceName": "연합뉴스 / 서울중앙지법",
    "sourceUrl": "https://www.yna.co.kr",
    "sourceType": "COURT",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["법정관리", "스마트폰", "상장폐지"],
    "affectedChannels": ["BANKRUPTCY", "LIQUIDATION"],
    "neutralAnalysis": {
      "verifiedFacts": "2014년 8월 19일 법정관리 신청, 누적 부채 1조 원 초과.",
      "impactChannels": ["BANKRUPTCY", "LIQUIDATION"],
      "positiveInterpretation": "없음.",
      "negativeInterpretation": "주식 거래정지 및 2015년 상장폐지 확정, 협력업체 연쇄 피해.",
      "unknownAtTheTime": "국내외 인수 대상자를 찾지 못해 청산 위기에 직면할지 여부."
    },
    "importanceScore": 9,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_1995_KR_003550",
    "scope": "COMPANY",
    "market": "KR",
    "canonicalCompanyIds": ["KR_003550"],
    "relatedTickers": ["003550"],
    "relatedSectors": ["지주사 / 화학·전자"],
    "eventDate": "1995-01-03",
    "publishedAt": "1995-01-03",
    "availableFrom": "1995-01-03",
    "datePrecision": "DAY",
    "originalTitle": "럭키금성그룹, 그룹 사명을 'LG'로 전격 변경하고 CI 선포",
    "titleKo": "럭키금성, 그룹 사명 'LG'로 변경 선포… 글로벌 도약 선언",
    "summaryKo": "럭키금성그룹이 1995년 새해를 맞아 그룹 명칭을 'LG(엘지)'로 전격 변경하고 새로운 CI를 발표했습니다. 화학(럭키)과 전자(금성)의 결합을 넘어 글로벌 일류 브랜드로 도약하겠다는 구본무 회장의 경영 혁신이 본격화됩니다.",
    "sourceName": "매일경제 / 조선일보",
    "sourceUrl": "https://www.mk.co.kr",
    "sourceType": "NEWS_AGENCY",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["사명변경", "지주사", "브랜드혁신"],
    "affectedChannels": ["BRAND_VALUE", "GLOBAL_EXPANSION"],
    "neutralAnalysis": {
      "verifiedFacts": "1995년 1월 3일 럭키금성에서 LG로 그룹명 및 주력 계열사명 통일 변경.",
      "impactChannels": ["BRAND_VALUE", "GLOBAL_EXPANSION"],
      "positiveInterpretation": "해외 소비자에게 친숙한 2글자 글로벌 프리미엄 브랜드 정립.",
      "negativeInterpretation": "CI 교체 및 글로벌 마케팅에 수천억 원의 비용 소요.",
      "unknownAtTheTime": "2003년 국내 최초 순수 지주회사 체제로 지배구조를 선진화할지 여부."
    },
    "importanceScore": 8,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_2008_US_LEH",
    "scope": "COMPANY",
    "market": "US",
    "canonicalCompanyIds": ["US_LEH"],
    "relatedTickers": ["LEH"],
    "relatedSectors": ["금융 / 투자은행"],
    "eventDate": "2008-09-15",
    "publishedAt": "2008-09-15",
    "availableFrom": "2008-09-15",
    "datePrecision": "DAY",
    "originalTitle": "Lehman Brothers Files for Chapter 11 Bankruptcy Protection",
    "titleKo": "[특보] 158년 역사 리만 브라더스 파산 신청… 글로벌 금융위기 폭발",
    "summaryKo": "미국 4대 투자은행 리만 브라더스가 서브프라임 모기지 손실과 부실자산 6,000억 달러를 감당하지 못하고 뉴욕 남부 파산법원에 챕터 11 파산 보호를 전격 신청했습니다. 미국 정부의 구제금융 거부로 세계 금융시장이 공황에 빠졌습니다.",
    "sourceName": "The Wall Street Journal / SEC",
    "sourceUrl": "https://www.wsj.com",
    "sourceType": "NEWS_AGENCY",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["파산", "금융위기", "투자은행"],
    "affectedChannels": ["BANKRUPTCY", "GLOBAL_LIQUIDITY_SHOCK"],
    "neutralAnalysis": {
      "verifiedFacts": "2008년 9월 15일 새벽 파산 신청, 자산 6,390억 달러 기준 미국 역사상 최대 규모 파산.",
      "impactChannels": ["BANKRUPTCY", "GLOBAL_LIQUIDITY_SHOCK"],
      "positiveInterpretation": "없음.",
      "negativeInterpretation": "리만 주가 $0.05로 폭락, AIG 구제금융 및 메릴린치 매각 등 연쇄 금융 패닉.",
      "unknownAtTheTime": "이 파산이 대공황 이후 최악의 글로벌 실물 경기 침체(Great Recession)로 번질지 여부."
    },
    "importanceScore": 10,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_2001_US_ENE",
    "scope": "COMPANY",
    "market": "US",
    "canonicalCompanyIds": ["US_ENE"],
    "relatedTickers": ["ENE"],
    "relatedSectors": ["에너지 / 금융 트레이딩"],
    "eventDate": "2001-12-02",
    "publishedAt": "2001-12-02",
    "availableFrom": "2001-12-02",
    "datePrecision": "DAY",
    "originalTitle": "Enron Files Chapter 11 Bankruptcy Following Massive Accounting Fraud",
    "titleKo": "[특보] 미국 7대 대기업 엔론, 사상 최대 분식회계로 파산 신청",
    "summaryKo": "포춘지 선정 6년 연속 '가장 혁신적인 기업'으로 꼽혔던 거대 에너지 기업 엔론이 특수목적법인(SPE)을 통해 수십억 달러의 부채를 숨기고 이익을 부풀린 회계부정이 폭로되어 챕터 11 파산을 신청했습니다.",
    "sourceName": "The New York Times / SEC",
    "sourceUrl": "https://www.nytimes.com",
    "sourceType": "NEWS_AGENCY",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["분식회계", "파산", "회계스캔들"],
    "affectedChannels": ["BANKRUPTCY", "REGULATION"],
    "neutralAnalysis": {
      "verifiedFacts": "2001년 12월 2일 파산 신청, 엔론 주가 $90에서 $0.1대로 폭락, 아서 앤더슨 회계법인 해체.",
      "impactChannels": ["BANKRUPTCY", "REGULATION"],
      "positiveInterpretation": "없음.",
      "negativeInterpretation": "주주 가치 전액 증발 및 직원 연금 펀드 파탄, 기업 회계 신뢰도 추락.",
      "unknownAtTheTime": "이 스캔들로 인해 미국 의회가 강력한 기업 회계개혁법인 사베인스-옥슬리법(SOX)을 제정할지 여부."
    },
    "importanceScore": 10,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_2007_US_BB",
    "scope": "COMPANY",
    "market": "US",
    "canonicalCompanyIds": ["US_BB", "US_AAPL"],
    "relatedTickers": ["BB", "AAPL"],
    "relatedSectors": ["빅테크 / 모바일·보안"],
    "eventDate": "2007-06-29",
    "publishedAt": "2007-06-29",
    "availableFrom": "2007-06-29",
    "datePrecision": "DAY",
    "originalTitle": "Apple Launches iPhone; BlackBerry Dismisses Touchscreen Threat",
    "titleKo": "애플 최초의 아이폰 출시… 블랙베리 경영진 '쿼티 자판이 표준' 일축",
    "summaryKo": "애플이 풀터치스크린 방식의 아이폰을 공식 출시했습니다. 글로벌 스마트폰 점유율 50%를 장악하고 있는 블랙베리(RIM) 경영진은 기업 고객들에게 물리적 쿼티 자판과 배터리 효율이 핵심이라며 아이폰의 파급력을 낮게 평가했습니다.",
    "sourceName": "The Wall Street Journal / Bloomberg",
    "sourceUrl": "https://www.bloomberg.com",
    "sourceType": "NEWS_AGENCY",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["스마트폰", "패러다임전환", "혁신"],
    "affectedChannels": ["COMPETITION", "TECH_DISRUPTION"],
    "neutralAnalysis": {
      "verifiedFacts": "2007년 6월 29일 미국 아이폰 판매 개시, 블랙베리 주가 100달러 돌파.",
      "impactChannels": ["COMPETITION", "TECH_DISRUPTION"],
      "positiveInterpretation": "블랙베리 기업용 이메일 보안 네트워크의 강력한 록인(Lock-in) 효과 신뢰.",
      "negativeInterpretation": "앱스토어 생태계와 정전식 터치스크린 대세화에 대비하지 못할 경우 치명적.",
      "unknownAtTheTime": "5년 후 블랙베리 스마트폰 점유율이 0%대로 추락하고 주가가 -95% 폭락할지 여부."
    },
    "importanceScore": 9,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_2010_US_BBI",
    "scope": "COMPANY",
    "market": "US",
    "canonicalCompanyIds": ["US_BBI"],
    "relatedTickers": ["BBI"],
    "relatedSectors": ["미디어 / 엔터테인먼트 유통"],
    "eventDate": "2010-09-23",
    "publishedAt": "2010-09-23",
    "availableFrom": "2010-09-23",
    "datePrecision": "DAY",
    "originalTitle": "Blockbuster Files Chapter 11 Bankruptcy Amid Netflix Streaming Rise",
    "titleKo": "[특보] 9천개 매장 비디오 제국 블록버스터 파산… 넷플릭스 OTT에 완패",
    "summaryKo": "전 세계 9,000개 매장과 수만 명의 직원을 보유했던 세계 최대 비디오/DVD 대여 체인 블록버스터가 넷플릭스의 디지털 스트리밍과 우편 대여 공세에 밀려 10억 달러의 부채를 감당하지 못하고 파산 보호를 신청했습니다.",
    "sourceName": "The New York Times / Reuters",
    "sourceUrl": "https://www.reuters.com",
    "sourceType": "NEWS_AGENCY",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["파산", "디지털전환", "OTT"],
    "affectedChannels": ["BANKRUPTCY", "DIGITAL_DISRUPTION"],
    "neutralAnalysis": {
      "verifiedFacts": "2010년 9월 23일 파산 신청, 2000년 넷플릭스 5천만 달러 인수 제안 거절 역사.",
      "impactChannels": ["BANKRUPTCY", "DIGITAL_DISRUPTION"],
      "positiveInterpretation": "없음.",
      "negativeInterpretation": "오프라인 매장 고정비 부담과 디지털 전환 실기가 부른 기업 붕괴.",
      "unknownAtTheTime": "넷플릭스가 향후 전 세계 2억 명 이상의 구독자를 보유한 미디어 제국으로 성장할지 여부."
    },
    "importanceScore": 9,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  },
  {
    "id": "COMP_2011_US_NOK",
    "scope": "COMPANY",
    "market": "US",
    "canonicalCompanyIds": ["US_NOK", "US_MSFT"],
    "relatedTickers": ["NOK", "MSFT"],
    "relatedSectors": ["통신장비 / 모바일"],
    "eventDate": "2011-02-11",
    "publishedAt": "2011-02-11",
    "availableFrom": "2011-02-11",
    "datePrecision": "DAY",
    "originalTitle": "Nokia CEO Stephen Elop Issues 'Burning Platform' Memo; Partners with Microsoft",
    "titleKo": "노키아 CEO '우리는 불타는 플랫폼 위에 있다' 선언… MS 윈도우폰 제휴",
    "summaryKo": "글로벌 1위 휴대폰 기업 노키아의 스티븐 엘롭 CEO가 임직원들에게 심비안(Symbian) 생태계의 패배를 인정하는 '불타는 플랫폼' 메모를 보내고, 안드로이드 대신 마이크로소프트 윈도우폰 플랫폼을 스마트폰 주력 OS로 채택하겠다고 발표했습니다.",
    "sourceName": "The Wall Street Journal / Financial Times",
    "sourceUrl": "https://www.ft.com",
    "sourceType": "NEWS_AGENCY",
    "evidenceLevel": "PRIMARY_SOURCE",
    "categories": ["스마트폰", "OS전략", "경영위기"],
    "affectedChannels": ["STRATEGY_SHIFT", "MARKET_SHARE"],
    "neutralAnalysis": {
      "verifiedFacts": "2011년 2월 11일 런던 전략 발표, 노키아-마이크로소프트 전략적 파트너십 체결.",
      "impactChannels": ["STRATEGY_SHIFT", "MARKET_SHARE"],
      "positiveInterpretation": "마이크로소프트와의 자금·소프트웨어 결합으로 애플/구글 양강에 제3 세력 구축 시도.",
      "negativeInterpretation": "개발자 생태계가 없는 윈도우폰 선택으로 소비자 이탈 가속화 위험.",
      "unknownAtTheTime": "2년 후 2013년 노키아가 휴대폰 사업부 전체를 마이크로소프트에 72억 달러에 매각하게 될지 여부."
    },
    "importanceScore": 9,
    "language": "ko",
    "isRetrospective": false,
    "fullTextStored": false,
    "dataQuality": "HIGH",
    "retrievedAt": "2026-08-26T00:00:00Z"
  }
]
"""

def main():
    print(f"Reading existing news from {NEWS_FILE}...")
    with open(NEWS_FILE, "r", encoding="utf-8") as f:
        existing_news = json.load(f)

    existing_ids = {n["id"] for n in existing_news}
    new_articles = json.loads(RAW_JSON_ARTICLES)
    added_count = 0

    for article in new_articles:
        if article["id"] not in existing_ids:
            existing_news.append(article)
            existing_ids.add(article["id"])
            added_count += 1

    # Sort chronological
    existing_news.sort(key=lambda x: (x["publishedAt"], x["id"]))

    for target in [NEWS_FILE, BACKUP_NEWS_FILE]:
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "w", encoding="utf-8") as f:
            json.dump(existing_news, f, ensure_ascii=False, indent=2)

    print(f"Successfully added {added_count} new historical articles. Total news: {len(existing_news)}")

if __name__ == "__main__":
    main()
