import json
import os

STOCKS_PATH = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'normalized', 'stocks.json')
OUT_EVENTS_PATH = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'universe', 'listing-events.json')
OUT_STOCKS_PATH = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'universe', 'historical-stocks.json')

os.makedirs(os.path.dirname(OUT_EVENTS_PATH), exist_ok=True)

with open(STOCKS_PATH, 'r', encoding='utf-8') as f:
    stocks = json.load(f)

# Accurate historical listing events data for 50 companies
LISTING_METADATA = {
    # === KOREA STOCKS (25) ===
    "KR_005930": { # 삼성전자
        "eventType": "IPO",
        "listingDate": "1975-06-11",
        "firstTradingDate": "1975-06-11",
        "companyName": "삼성전자공업",
        "ticker": "005930",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "전기전자",
        "business": "흑백 TV 및 반도체·전자부품 제조",
        "ipoPrice": None,
        "firstPrice": 11061,
        "officialTitle": "한국증권거래소 삼성전자공업(주) 신규 상장 공시",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1975_005930", "COMP_1983_KR_005930"]
    },
    "KR_000660": { # SK하이닉스
        "eventType": "IPO",
        "listingDate": "1996-12-26",
        "firstTradingDate": "1996-12-26",
        "companyName": "현대전자산업",
        "ticker": "000660",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "반도체",
        "business": "DRAM 반도체 및 정보통신 단말기 제조",
        "ipoPrice": 18000,
        "firstPrice": 17500,
        "officialTitle": "현대전자산업(주) 기업공개(IPO) 및 주권 신규상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1996_000660", "COMP_1996_KR_000660"]
    },
    "KR_005380": { # 현대차
        "eventType": "IPO",
        "listingDate": "1974-06-28",
        "firstTradingDate": "1974-06-28",
        "companyName": "현대자동차",
        "ticker": "005380",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "자동차",
        "business": "완성차(코티나, 포니) 및 상용차 제조",
        "ipoPrice": None,
        "firstPrice": 3850,
        "officialTitle": "현대자동차(주) 유가증권시장 주권 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1974_005380", "COMP_1985_KR_005380"]
    },
    "KR_000270": { # 기아
        "eventType": "IPO",
        "listingDate": "1973-07-21",
        "firstTradingDate": "1973-07-21",
        "companyName": "기아산업",
        "ticker": "000270",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "자동차",
        "business": "삼륜차 및 승용차·화물차 제조",
        "ipoPrice": None,
        "firstPrice": 2400,
        "officialTitle": "기아산업(주) 증권거래소 신규 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1973_000270"]
    },
    "KR_051910": { # LG화학
        "eventType": "SPINOFF_LISTING",
        "listingDate": "2001-04-25",
        "firstTradingDate": "2001-04-25",
        "companyName": "LG화학",
        "ticker": "051910",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "석유화학 / 배터리",
        "business": "석유화학 기초소재 및 2차전지 제조",
        "ipoPrice": None,
        "firstPrice": 14200,
        "officialTitle": "LG화학(주) 분할 재상장 승인 공시",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2001_051910"]
    },
    "KR_005490": { # POSCO홀딩스
        "eventType": "IPO",
        "listingDate": "1988-06-10",
        "firstTradingDate": "1988-06-10",
        "companyName": "포항종합제철",
        "ticker": "005490",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "철강",
        "business": "일관제철소 조강 및 철강 판재류 생산",
        "ipoPrice": 15000,
        "firstPrice": 43000,
        "officialTitle": "포항종합제철 국민주 1호 유가증권시장 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1988_005490", "COMP_1988_KR_005490"]
    },
    "KR_035420": { # NAVER
        "eventType": "IPO",
        "listingDate": "2002-10-29",
        "firstTradingDate": "2002-10-29",
        "companyName": "NHN(네이버컴)",
        "ticker": "035420",
        "exchange": "코스닥시장(2008년 유가증권시장 이전)",
        "sector": "인터넷 / 플랫폼",
        "business": "인터넷 포털 네이버 검색 및 한게임 온라인 서비스",
        "ipoPrice": 22000,
        "firstPrice": 44000,
        "officialTitle": "엔에이치엔(주) 코스닥시장 신규 등록",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2002_035420", "COMP_2002_KR_035420"]
    },
    "KR_035720": { # 카카오
        "eventType": "MERGER_LISTING",
        "listingDate": "1999-11-11",
        "firstTradingDate": "1999-11-11",
        "companyName": "다음커뮤니케이션",
        "ticker": "035720",
        "exchange": "코스닥시장(2017년 유가증권시장 이전)",
        "sector": "인터넷 / 모바일",
        "business": "한메일넷 및 미디어다음 인터넷 포털",
        "ipoPrice": 8500,
        "firstPrice": 15600,
        "officialTitle": "다음커뮤니케이션 코스닥시장 신규 등록",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1999_035720"]
    },
    "KR_207940": { # 삼성바이오로직스
        "eventType": "IPO",
        "listingDate": "2016-11-10",
        "firstTradingDate": "2016-11-10",
        "companyName": "삼성바이오로직스",
        "ticker": "207940",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "바이오 / 제약",
        "business": "바이오의약품 위탁개발생산(CDMO)",
        "ipoPrice": 136000,
        "firstPrice": 144000,
        "officialTitle": "삼성바이오로직스(주) 유가증권시장 신규상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2016_207940", "COMP_2016_KR_207940"]
    },
    "KR_068270": { # 셀트리온
        "eventType": "RELISTING",
        "listingDate": "2005-07-19",
        "firstTradingDate": "2005-07-19",
        "companyName": "셀트리온(넥스솔)",
        "ticker": "068270",
        "exchange": "코스닥시장(2018년 유가증권시장 이전)",
        "sector": "바이오시밀러",
        "business": "바이오시밀러 및 단일클론항체 치료제 개발",
        "ipoPrice": None,
        "firstPrice": 8500,
        "officialTitle": "셀트리온 코스닥 우회상장 및 신규 거래",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2005_068270"]
    },
    "KR_006400": { # 삼성SDI
        "eventType": "IPO",
        "listingDate": "1979-02-27",
        "firstTradingDate": "1979-02-27",
        "companyName": "삼성전관",
        "ticker": "006400",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "2차전지 / 디스플레이",
        "business": "브라운관(CRT) 및 2차전지 배터리",
        "ipoPrice": None,
        "firstPrice": 2100,
        "officialTitle": "삼성전관(주) 증권거래소 주권 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1979_006400"]
    },
    "KR_066570": { # LG전자
        "eventType": "SPINOFF_LISTING",
        "listingDate": "2002-04-22",
        "firstTradingDate": "2002-04-22",
        "companyName": "LG전자",
        "ticker": "066570",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "가전 / IT",
        "business": "가전제품 및 디지털 디스플레이, 모바일 기기",
        "ipoPrice": None,
        "firstPrice": 19500,
        "officialTitle": "LG전자(주) 지주회사 전환 분할 신규 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2002_066570"]
    },
    "KR_017670": { # SK텔레콤
        "eventType": "IPO",
        "listingDate": "1989-11-08",
        "firstTradingDate": "1989-11-08",
        "companyName": "한국이동통신",
        "ticker": "017670",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "통신",
        "business": "무선호출(삐삐) 및 이동전화 서비스",
        "ipoPrice": 12000,
        "firstPrice": 24000,
        "officialTitle": "한국이동통신서비스(주) 주식 신규 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1989_017670", "COMP_1989_KR_017670"]
    },
    "KR_012330": { # 현대모비스
        "eventType": "IPO",
        "listingDate": "1989-09-05",
        "firstTradingDate": "1989-09-05",
        "companyName": "현대정공",
        "ticker": "012330",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "자동차부품",
        "business": "컨테이너선 박스 및 자동차 핵심 모듈 부품",
        "ipoPrice": None,
        "firstPrice": 15000,
        "officialTitle": "현대정공(주) 한국증권거래소 신규 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1989_012330"]
    },
    "KR_105560": { # KB금융
        "eventType": "SPINOFF_LISTING",
        "listingDate": "2008-10-10",
        "firstTradingDate": "2008-10-10",
        "companyName": "KB금융지주",
        "ticker": "105560",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "금융 / 은행",
        "business": "국민은행 등 금융자회사 종합 관리",
        "ipoPrice": None,
        "firstPrice": 44800,
        "officialTitle": "KB금융지주 포괄적 주식이전 신규 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2008_105560"]
    },
    "KR_055550": { # 신한지주
        "eventType": "IPO",
        "listingDate": "2001-09-10",
        "firstTradingDate": "2001-09-10",
        "companyName": "신한금융지주회사",
        "ticker": "055550",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "금융 / 은행",
        "business": "신한은행 및 금융 자회사 지주회사",
        "ipoPrice": None,
        "firstPrice": 12500,
        "officialTitle": "신한금융지주회사 주권 신규 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2001_055550"]
    },
    "KR_096770": { # SK이노베이션
        "eventType": "SPINOFF_LISTING",
        "listingDate": "2007-07-25",
        "firstTradingDate": "2007-07-25",
        "companyName": "SK에너지",
        "ticker": "096770",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "에너지 / 정유",
        "business": "석유정제, 석유화학, 2차전지 배터리",
        "ipoPrice": None,
        "firstPrice": 137000,
        "officialTitle": "SK(주) 사업회사 분할에 따른 SK에너지 재상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2007_096770"]
    },
    "KR_028260": { # 삼성물산
        "eventType": "MERGER_LISTING",
        "listingDate": "2014-12-18",
        "firstTradingDate": "2014-12-18",
        "companyName": "제일모직(현 삼성물산)",
        "ticker": "028260",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "지주 / 건설·상사",
        "business": "패션, 리조트 및 건설·상사 부문",
        "ipoPrice": 53000,
        "firstPrice": 106000,
        "officialTitle": "제일모직(주) 유가증권시장 신규 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2014_028260"]
    },
    "KR_032830": { # 삼성생명
        "eventType": "IPO",
        "listingDate": "2010-05-12",
        "firstTradingDate": "2010-05-12",
        "companyName": "삼성생명보험",
        "ticker": "032830",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "금융 / 보험",
        "business": "생명보험 및 개인·기업 금융서비스",
        "ipoPrice": 110000,
        "firstPrice": 119500,
        "officialTitle": "삼성생명보험(주) 유가증권시장 초대형 IPO 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2010_032830"]
    },
    "KR_086790": { # 하나금융지주
        "eventType": "SPINOFF_LISTING",
        "listingDate": "2005-12-12",
        "firstTradingDate": "2005-12-12",
        "companyName": "하나금융지주",
        "ticker": "086790",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "금융 / 은행",
        "business": "하나은행 등 자회사 관리 금융지주",
        "ipoPrice": None,
        "firstPrice": 41200,
        "officialTitle": "하나금융지주회사 주식 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2005_086790"]
    },
    "KR_003550": { # LG
        "eventType": "IPO",
        "listingDate": "1970-02-13",
        "firstTradingDate": "1970-02-13",
        "companyName": "럭키",
        "ticker": "003550",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "지주사",
        "business": "LG그룹 순수 지주회사",
        "ipoPrice": None,
        "firstPrice": 1500,
        "officialTitle": "락희화학공업사 증권거래소 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1970_003550"]
    },
    "KR_010130": { # 고려아연
        "eventType": "IPO",
        "listingDate": "1990-07-28",
        "firstTradingDate": "1990-07-28",
        "companyName": "고려아연",
        "ticker": "010130",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "비철금속",
        "business": "아연, 연, 금, 은 등 비철금속 제련",
        "ipoPrice": None,
        "firstPrice": 18500,
        "officialTitle": "고려아연(주) 유가증권시장 신규상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1990_010130"]
    },
    "KR_034730": { # SK
        "eventType": "IPO",
        "listingDate": "2009-11-11",
        "firstTradingDate": "2009-11-11",
        "companyName": "SK C&C(현 SK)",
        "ticker": "034730",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "지주 / IT서비스",
        "business": "IT 시스템 통합 및 SK그룹 지주회사",
        "ipoPrice": 30000,
        "firstPrice": 31500,
        "officialTitle": "에스케이씨앤씨(주) 주권 신규상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2009_034730"]
    },
    "KR_018260": { # 삼성에스디에스
        "eventType": "IPO",
        "listingDate": "2014-11-14",
        "firstTradingDate": "2014-11-14",
        "companyName": "삼성에스디에스",
        "ticker": "018260",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "IT서비스 / 클라우드",
        "business": "기업용 IT 솔루션 및 디지털 물류",
        "ipoPrice": 190000,
        "firstPrice": 380000,
        "officialTitle": "삼성에스디에스(주) 유가증권시장 신규상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_2014_018260"]
    },
    "KR_009150": { # 삼성전기
        "eventType": "IPO",
        "listingDate": "1979-02-27",
        "firstTradingDate": "1979-02-27",
        "companyName": "삼성전자부품",
        "ticker": "009150",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "전자부품 / MLCC",
        "business": "MLCC(적층세라믹콘덴서) 및 카메라 모듈",
        "ipoPrice": None,
        "firstPrice": 1800,
        "officialTitle": "삼성산전부품공업(주) 주권 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1979_009150"]
    },
    "KR_001600": { # 한보철강
        "eventType": "IPO",
        "listingDate": "1989-11-20",
        "firstTradingDate": "1989-11-20",
        "companyName": "한보철강공업",
        "ticker": "001600",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "철강 / 중공업",
        "business": "봉강, 철근 제조 및 당진 코렉스 제철소 건설",
        "ipoPrice": 16000,
        "firstPrice": 22000,
        "officialTitle": "한보철강공업(주) 주권 신규상장 공시",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1989_001600", "COMP_1989_KR_001600"]
    },
    "KR_000010": { # 제일은행
        "eventType": "IPO",
        "listingDate": "1956-03-03",
        "firstTradingDate": "1956-03-03",
        "companyName": "제일은행",
        "ticker": "000010",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "금융 / 은행",
        "business": "시중은행 금융업 및 예적금, 대기업 여신 지원",
        "ipoPrice": None,
        "firstPrice": 1100,
        "officialTitle": "제일은행 주권 상장 (대한민국 제1호 상장 은행)",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1956_000010", "COMP_1980_KR_000010"]
    },
    "KR_001300": { # (주)대우
        "eventType": "IPO",
        "listingDate": "1975-10-07",
        "firstTradingDate": "1975-10-07",
        "companyName": "대우실업",
        "ticker": "001300",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "종합상사 / 무역",
        "business": "섬유·중화학 수출입 종합상사 및 세계경영 해외 네트워크",
        "ipoPrice": None,
        "firstPrice": 850,
        "officialTitle": "대우실업(주) 유가증권시장 주권 상장",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1975_001300", "COMP_1980_KR_001300"]
    },
    "KR_025930": { # 팬택
        "eventType": "IPO",
        "listingDate": "1999-12-07",
        "firstTradingDate": "1999-12-07",
        "companyName": "팬택",
        "ticker": "025930",
        "exchange": "코스닥 / 한국거래소",
        "sector": "IT / 스마트폰",
        "business": "무선호출기(삐삐) 및 CDMA 모바일 휴대폰 단말기 제조",
        "ipoPrice": 12500,
        "firstPrice": 18500,
        "officialTitle": "팬택(주) 코스닥시장 신규등록 공시",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1999_025930", "COMP_1999_KR_025930"]
    },
    "KR_003550": { # LG
        "eventType": "IPO",
        "listingDate": "1970-02-13",
        "firstTradingDate": "1970-02-13",
        "companyName": "럭키",
        "ticker": "003550",
        "exchange": "한국거래소(유가증권시장)",
        "sector": "지주사 / 화학·전자",
        "business": "플라스틱 가공, 세제·치약 및 계열 지분 보유",
        "ipoPrice": None,
        "firstPrice": 450,
        "officialTitle": "럭키(주) 주권 상장 공시",
        "officialUrl": "https://kind.krx.co.kr",
        "relatedNewsIds": ["KRX_LIST_1970_003550", "COMP_1980_KR_003550"]
    },

    # === US STOCKS (30) ===
    "US_AAPL": { # Apple
        "eventType": "IPO",
        "listingDate": "1980-12-12",
        "firstTradingDate": "1980-12-12",
        "companyName": "Apple Computer, Inc.",
        "ticker": "AAPL",
        "exchange": "NASDAQ",
        "sector": "Consumer Tech / Hardware",
        "business": "Personal Computers (Apple II, III)",
        "ipoPrice": 22.0,
        "firstPrice": 29.0,
        "officialTitle": "Apple Computer, Inc. Initial Public Offering on NASDAQ",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_1980_AAPL", "COMP_1980_US_AAPL"]
    },
    "US_MSFT": { # Microsoft
        "eventType": "IPO",
        "listingDate": "1986-03-13",
        "firstTradingDate": "1986-03-13",
        "companyName": "Microsoft Corporation",
        "ticker": "MSFT",
        "exchange": "NASDAQ",
        "sector": "Software / OS",
        "business": "MS-DOS, Windows operating systems and BASIC compilers",
        "ipoPrice": 21.0,
        "firstPrice": 27.75,
        "officialTitle": "Microsoft Corporation Initial Public Offering on NASDAQ",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_1986_MSFT", "COMP_1986_US_MSFT"]
    },
    "US_NVDA": { # Nvidia
        "eventType": "IPO",
        "listingDate": "1999-01-22",
        "firstTradingDate": "1999-01-22",
        "companyName": "NVIDIA Corporation",
        "ticker": "NVDA",
        "exchange": "NASDAQ",
        "sector": "Semiconductors / GPU",
        "business": "3D Graphics Processing Units (RIVA 128, TNT)",
        "ipoPrice": 12.0,
        "firstPrice": 12.0,
        "officialTitle": "NVIDIA Corporation IPO Prospectus Filed with SEC",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_1999_NVDA", "COMP_1999_US_NVDA"]
    },
    "US_AMZN": { # Amazon
        "eventType": "IPO",
        "listingDate": "1997-05-15",
        "firstTradingDate": "1997-05-15",
        "companyName": "Amazon.com, Inc.",
        "ticker": "AMZN",
        "exchange": "NASDAQ",
        "sector": "E-Commerce / Cloud",
        "business": "Online bookstore and e-commerce marketplace",
        "ipoPrice": 18.0,
        "firstPrice": 18.0,
        "officialTitle": "Amazon.com Initial Public Offering on NASDAQ",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_1997_AMZN", "COMP_1997_US_AMZN"]
    },
    "US_GOOGL": { # Alphabet (Google)
        "eventType": "IPO",
        "listingDate": "2004-08-19",
        "firstTradingDate": "2004-08-19",
        "companyName": "Google Inc.",
        "ticker": "GOOG",
        "exchange": "NASDAQ",
        "sector": "Internet Search / Advertising",
        "business": "Online search engine and AdWords advertising platform",
        "ipoPrice": 85.0,
        "firstPrice": 100.34,
        "officialTitle": "Google Inc. Form S-1 Registration Statement (Dutch Auction IPO)",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_2004_GOOGL", "COMP_2004_US_GOOGL"]
    },
    "US_META": { # Meta (Facebook)
        "eventType": "IPO",
        "listingDate": "2012-05-18",
        "firstTradingDate": "2012-05-18",
        "companyName": "Facebook, Inc.",
        "ticker": "FB",
        "exchange": "NASDAQ",
        "sector": "Social Media / Digital Ads",
        "business": "Global social networking platform (Facebook)",
        "ipoPrice": 38.0,
        "firstPrice": 38.23,
        "officialTitle": "Facebook, Inc. Initial Public Offering on NASDAQ",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_2012_META", "COMP_2012_US_META"]
    },
    "US_TSLA": { # Tesla
        "eventType": "IPO",
        "listingDate": "2010-06-29",
        "firstTradingDate": "2010-06-29",
        "companyName": "Tesla Motors, Inc.",
        "ticker": "TSLA",
        "exchange": "NASDAQ",
        "sector": "Electric Vehicles / Clean Energy",
        "business": "Electric sports cars (Tesla Roadster) and powertrain systems",
        "ipoPrice": 17.0,
        "firstPrice": 17.0,
        "officialTitle": "Tesla Motors, Inc. Initial Public Offering on NASDAQ",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_2010_TSLA", "COMP_2010_US_TSLA"]
    },
    "US_BRK_B": { # Berkshire Hathaway
        "eventType": "IPO",
        "listingDate": "1980-01-01",
        "firstTradingDate": "1980-01-01",
        "companyName": "Berkshire Hathaway Inc.",
        "ticker": "BRK",
        "exchange": "NYSE",
        "sector": "Financial Conglomerate / Insurance",
        "business": "Property and casualty insurance (GEICO) and value investing",
        "ipoPrice": None,
        "firstPrice": 290.0,
        "officialTitle": "Berkshire Hathaway Inc. Historical Listing on NYSE",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_1980_BRK"]
    },
    "US_JNJ": { # Johnson & Johnson
        "eventType": "IPO",
        "listingDate": "1944-09-25",
        "firstTradingDate": "1980-01-01",
        "companyName": "Johnson & Johnson",
        "ticker": "JNJ",
        "exchange": "NYSE",
        "sector": "Healthcare / Pharmaceuticals",
        "business": "Medical devices, pharmaceuticals, and consumer health",
        "ipoPrice": None,
        "firstPrice": 2.5,
        "officialTitle": "Johnson & Johnson Historical Trading Records",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_1980_JNJ"]
    },
    "US_JPM": { # JPMorgan Chase
        "eventType": "MERGER_LISTING",
        "listingDate": "1980-01-01",
        "firstTradingDate": "1980-01-01",
        "companyName": "Chemical Bank / J.P. Morgan & Co.",
        "ticker": "JPM",
        "exchange": "NYSE",
        "sector": "Banking / Financial Services",
        "business": "Commercial and investment banking, asset management",
        "ipoPrice": None,
        "firstPrice": 5.0,
        "officialTitle": "JPMorgan Chase & Co. NYSE Listing",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_1980_JPM"]
    },
    "US_V": { # Visa
        "eventType": "IPO",
        "listingDate": "2008-03-19",
        "firstTradingDate": "2008-03-19",
        "companyName": "Visa Inc.",
        "ticker": "V",
        "exchange": "NYSE",
        "sector": "Payment Technology",
        "business": "Global digital payments processing network",
        "ipoPrice": 44.0,
        "firstPrice": 56.5,
        "officialTitle": "Visa Inc. Record-Breaking Initial Public Offering on NYSE",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_2008_V", "COMP_2008_US_V"]
    },
    "US_WMT": { # Walmart
        "eventType": "IPO",
        "listingDate": "1972-08-25",
        "firstTradingDate": "1980-01-01",
        "companyName": "Wal-Mart Stores, Inc.",
        "ticker": "WMT",
        "exchange": "NYSE",
        "sector": "Retail / Consumer Staples",
        "business": "Discount department stores and grocery chain",
        "ipoPrice": None,
        "firstPrice": 0.8,
        "officialTitle": "Wal-Mart Stores Inc. Listing on NYSE",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_1980_WMT"]
    },
    "US_PG": { # Procter & Gamble
        "eventType": "IPO",
        "listingDate": "1980-01-01",
        "firstTradingDate": "1980-01-01",
        "companyName": "The Procter & Gamble Company",
        "ticker": "PG",
        "exchange": "NYSE",
        "sector": "Consumer Staples",
        "business": "Personal care, cleaning, and hygiene products",
        "ipoPrice": None,
        "firstPrice": 3.0,
        "officialTitle": "The Procter & Gamble Company NYSE Listing",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_1980_PG"]
    },
    "US_MA": { # Mastercard
        "eventType": "IPO",
        "listingDate": "2006-05-25",
        "firstTradingDate": "2006-05-25",
        "companyName": "Mastercard Incorporated",
        "ticker": "MA",
        "exchange": "NYSE",
        "sector": "Payment Technology",
        "business": "Global payments and transaction processing network",
        "ipoPrice": 39.0,
        "firstPrice": 46.0,
        "officialTitle": "Mastercard Inc. Initial Public Offering on NYSE",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_2006_MA"]
    },
    "US_HD": { # Home Depot
        "eventType": "IPO",
        "listingDate": "1981-09-22",
        "firstTradingDate": "1981-09-22",
        "companyName": "The Home Depot, Inc.",
        "ticker": "HD",
        "exchange": "NYSE",
        "sector": "Retail / Home Improvement",
        "business": "Home improvement retail warehouse stores",
        "ipoPrice": 12.0,
        "firstPrice": 12.0,
        "officialTitle": "The Home Depot, Inc. IPO on NASDAQ",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_1981_HD"]
    },
    "US_UNH": { # UnitedHealth Group
        "eventType": "IPO",
        "listingDate": "1984-10-18",
        "firstTradingDate": "1984-10-18",
        "companyName": "United HealthCare Corporation",
        "ticker": "UNH",
        "exchange": "NYSE",
        "sector": "Healthcare / Managed Care",
        "business": "Managed healthcare plans and health insurance",
        "ipoPrice": None,
        "firstPrice": 0.5,
        "officialTitle": "United HealthCare Corporation IPO",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_1984_UNH"]
    },
    "US_AVGO": { # Broadcom
        "eventType": "IPO",
        "listingDate": "2009-08-06",
        "firstTradingDate": "2009-08-06",
        "companyName": "Avago Technologies Limited",
        "ticker": "AVGO",
        "exchange": "NASDAQ",
        "sector": "Semiconductors / Infrastructure",
        "business": "Analog, wireless, and optical semiconductor components",
        "ipoPrice": 15.0,
        "firstPrice": 16.0,
        "officialTitle": "Avago Technologies (Broadcom) IPO on NASDAQ",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_2009_AVGO"]
    },
    "US_XOM": { # ExxonMobil
        "eventType": "IPO",
        "listingDate": "1980-01-01",
        "firstTradingDate": "1980-01-01",
        "companyName": "Exxon Corporation",
        "ticker": "XOM",
        "exchange": "NYSE",
        "sector": "Energy / Oil & Gas",
        "business": "Petroleum exploration, refining, and petrochemicals",
        "ipoPrice": None,
        "firstPrice": 2.0,
        "officialTitle": "Exxon Corporation NYSE Listing",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_1980_XOM"]
    },
    "US_KO": { # Coca-Cola
        "eventType": "IPO",
        "listingDate": "1980-01-01",
        "firstTradingDate": "1980-01-01",
        "companyName": "The Coca-Cola Company",
        "ticker": "KO",
        "exchange": "NYSE",
        "sector": "Beverages / Consumer Staples",
        "business": "Non-alcoholic beverage syrups and concentrates",
        "ipoPrice": None,
        "firstPrice": 1.2,
        "officialTitle": "The Coca-Cola Company Historical NYSE Listing",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_1980_KO"]
    },
    "US_PEP": { # PepsiCo
        "eventType": "IPO",
        "listingDate": "1980-01-01",
        "firstTradingDate": "1980-01-01",
        "companyName": "PepsiCo, Inc.",
        "ticker": "PEP",
        "exchange": "NASDAQ",
        "sector": "Food & Beverage",
        "business": "Carbonated soft drinks and Frito-Lay snack foods",
        "ipoPrice": None,
        "firstPrice": 1.5,
        "officialTitle": "PepsiCo, Inc. Listing Records",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_1980_PEP"]
    },
    "US_COST": { # Costco
        "eventType": "IPO",
        "listingDate": "1985-12-05",
        "firstTradingDate": "1985-12-05",
        "companyName": "Costco Wholesale Corporation",
        "ticker": "COST",
        "exchange": "NASDAQ",
        "sector": "Retail / Wholesale Club",
        "business": "Membership warehouse club retailing",
        "ipoPrice": 10.0,
        "firstPrice": 10.0,
        "officialTitle": "Costco Wholesale Corporation Initial Public Offering",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_1985_COST"]
    },
    "US_LLY": { # Eli Lilly
        "eventType": "IPO",
        "listingDate": "1980-01-01",
        "firstTradingDate": "1980-01-01",
        "companyName": "Eli Lilly and Company",
        "ticker": "LLY",
        "exchange": "NYSE",
        "sector": "Pharmaceuticals",
        "business": "Pharmaceutical development (Insulin, Prozac, Mounjaro)",
        "ipoPrice": None,
        "firstPrice": 2.0,
        "officialTitle": "Eli Lilly and Company Historical NYSE Listing",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_1980_LLY"]
    },
    "US_ABBV": { # AbbVie
        "eventType": "SPINOFF_LISTING",
        "listingDate": "2013-01-02",
        "firstTradingDate": "2013-01-02",
        "companyName": "AbbVie Inc.",
        "ticker": "ABBV",
        "exchange": "NYSE",
        "sector": "Biotechnology / Pharma",
        "business": "Specialty biopharmaceuticals (Humira, Skyrizi)",
        "ipoPrice": None,
        "firstPrice": 34.0,
        "officialTitle": "AbbVie Inc. Spinoff from Abbott Laboratories and NYSE Listing",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_2013_ABBV"]
    },
    "US_MRK": { # Merck & Co.
        "eventType": "IPO",
        "listingDate": "1980-01-01",
        "firstTradingDate": "1980-01-01",
        "companyName": "Merck & Co., Inc.",
        "ticker": "MRK",
        "exchange": "NYSE",
        "sector": "Healthcare / Pharmaceuticals",
        "business": "Prescription medicines, vaccines, and animal health",
        "ipoPrice": None,
        "firstPrice": 1.8,
        "officialTitle": "Merck & Co., Inc. Historical NYSE Listing",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_1980_MRK"]
    },
    "US_NFLX": { # Netflix
        "eventType": "IPO",
        "listingDate": "2002-05-23",
        "firstTradingDate": "2002-05-23",
        "companyName": "Netflix, Inc.",
        "ticker": "NFLX",
        "exchange": "NASDAQ",
        "sector": "Digital Streaming / Entertainment",
        "business": "Subscription DVD-by-mail and streaming media service",
        "ipoPrice": 15.0,
        "firstPrice": 15.0,
        "officialTitle": "Netflix, Inc. Initial Public Offering on NASDAQ",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_2002_NFLX"]
    },
    "US_LEH": { # Lehman Brothers
        "eventType": "IPO",
        "listingDate": "1994-05-27",
        "firstTradingDate": "1994-05-27",
        "companyName": "Lehman Brothers Holdings Inc.",
        "ticker": "LEH",
        "exchange": "NYSE",
        "sector": "Investment Banking / Finance",
        "business": "Global investment banking, fixed income and securities trading",
        "ipoPrice": 4.25,
        "firstPrice": 4.25,
        "officialTitle": "Lehman Brothers Holdings Inc. Spin-off IPO from American Express",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_1994_LEH", "COMP_1994_US_LEH"]
    },
    "US_ENE": { # Enron
        "eventType": "IPO",
        "listingDate": "1985-07-16",
        "firstTradingDate": "1985-07-16",
        "companyName": "Enron Corp.",
        "ticker": "ENE",
        "exchange": "NYSE",
        "sector": "Energy / Commodities Trading",
        "business": "Natural gas pipelines, electricity generation and energy derivatives",
        "ipoPrice": 2.80,
        "firstPrice": 2.80,
        "officialTitle": "Enron Corp. Form 8-K Merger and Listing Document",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_1985_ENE", "COMP_1985_US_ENE"]
    },
    "US_BB": { # BlackBerry / RIM
        "eventType": "IPO",
        "listingDate": "1999-02-04",
        "firstTradingDate": "1999-02-04",
        "companyName": "Research In Motion Limited",
        "ticker": "RIMM",
        "exchange": "NASDAQ",
        "sector": "Consumer Tech / Mobile",
        "business": "Two-way wireless pagers, BlackBerry enterprise email devices and software",
        "ipoPrice": 2.80,
        "firstPrice": 2.80,
        "officialTitle": "Research In Motion Initial Public Offering on NASDAQ",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_1999_RIMM", "COMP_1999_US_BB"]
    },
    "US_BBI": { # Blockbuster
        "eventType": "IPO",
        "listingDate": "1999-08-11",
        "firstTradingDate": "1999-08-11",
        "companyName": "Blockbuster Inc.",
        "ticker": "BBI",
        "exchange": "NYSE",
        "sector": "Media / Retail Rental",
        "business": "Home video and video game rental retail stores network",
        "ipoPrice": 15.0,
        "firstPrice": 15.0,
        "officialTitle": "Blockbuster Inc. Initial Public Offering on NYSE",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_1999_BBI", "COMP_1999_US_BBI"]
    },
    "US_NOK": { # Nokia
        "eventType": "IPO",
        "listingDate": "1994-07-01",
        "firstTradingDate": "1994-07-01",
        "companyName": "Nokia Corporation",
        "ticker": "NOK",
        "exchange": "NYSE (ADR)",
        "sector": "Telecommunications / Mobile Phones",
        "business": "GSM cellular mobile phones, network infrastructure and telecom equipment",
        "ipoPrice": 2.20,
        "firstPrice": 2.20,
        "officialTitle": "Nokia Corporation American Depositary Shares Listing on NYSE",
        "officialUrl": "https://www.sec.gov",
        "relatedNewsIds": ["SEC_IPO_1994_NOK", "COMP_1994_US_NOK"]
    }
}

ALIASES_PATH = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'news', 'entity-aliases.json')
aliases_by_id = {}
if os.path.exists(ALIASES_PATH):
    with open(ALIASES_PATH, 'r', encoding='utf-8') as f:
        raw_aliases = json.load(f)
        for al in raw_aliases:
            cid = al["canonicalCompanyId"]
            if cid not in aliases_by_id:
                aliases_by_id[cid] = []
            clean_name = al["historicalName"].replace("(주)", "").replace("(유)", "").strip()
            aliases_by_id[cid].append({
                "validFrom": al["validFrom"],
                "validTo": al["validTo"] if al["validTo"] != "9999-12-31" else None,
                "name": clean_name,
                "ticker": al.get("ticker", "")
            })

listing_events = []
historical_stocks = []

for stock in stocks:
    cid = stock["canonicalId"]
    meta = LISTING_METADATA.get(cid, {
        "eventType": "IPO",
        "listingDate": stock.get("listingDate", "1980-01-01"),
        "firstTradingDate": stock.get("listingDate", "1980-01-01"),
        "companyName": stock["nameKo"],
        "ticker": stock["ticker"],
        "exchange": "KRX" if stock["market"] == "KR" else "NASDAQ/NYSE",
        "sector": stock["sector"],
        "business": stock["description"],
        "ipoPrice": None,
        "firstPrice": 1000 if stock["market"] == "KR" else 10.0,
        "officialTitle": f"{stock['nameKo']} 상장 자료",
        "officialUrl": "https://kind.krx.co.kr" if stock["market"] == "KR" else "https://www.sec.gov",
        "relatedNewsIds": []
    })

    event_id = f"LISTING_EVENT_{cid}"
    listing_event = {
        "id": event_id,
        "canonicalCompanyId": cid,
        "eventType": meta["eventType"],
        "listingDate": meta["listingDate"],
        "firstTradingDate": meta["firstTradingDate"],
        "datePrecision": "DAY",
        "companyNameAsOfDate": meta["companyName"],
        "tickerAsOfDate": meta["ticker"],
        "exchangeAsOfDate": meta["exchange"],
        "sectorAsOfDate": meta["sector"],
        "businessSummaryAsOfDate": meta["business"],
        "officialAnnouncementTitle": meta["officialTitle"],
        "officialAnnouncementUrl": meta["officialUrl"],
        "relatedNewsIds": meta["relatedNewsIds"],
        "firstValidPriceDate": meta["firstTradingDate"],
        "firstValidPrice": meta["firstPrice"],
        "ipoOfferingPrice": meta["ipoPrice"],
        "dataQuality": "HIGH",
        "isTradableImmediately": True
    }
    listing_events.append(listing_event)

    name_hist = aliases_by_id.get(cid, [
        {"validFrom": meta["firstTradingDate"], "name": meta["companyName"], "ticker": meta["ticker"]}
    ])
    # Also ensure currentName is in name_hist as fallback
    if not name_hist:
        name_hist = [{"validFrom": meta["firstTradingDate"], "name": stock["nameKo"], "ticker": stock["ticker"]}]

    historical_stock = {
        "canonicalCompanyId": cid,
        "currentTicker": stock["ticker"],
        "currentName": stock["nameKo"],
        "market": stock["market"],
        "currency": stock["currency"],
        "listingDate": meta["listingDate"],
        "firstTradingDate": meta["firstTradingDate"],
        "firstValidPriceDate": meta["firstTradingDate"],
        "delistingDate": stock.get("delistingDate"),
        "nameHistory": name_hist,
        "sectorHistory": [
            {"validFrom": meta["firstTradingDate"], "sector": meta["sector"]}
        ],
        "listingEventId": event_id,
        "listingNewsIds": meta["relatedNewsIds"],
        "dataQuality": "HIGH",
        "description": stock["description"]
    }
    historical_stocks.append(historical_stock)


with open(OUT_EVENTS_PATH, 'w', encoding='utf-8') as f:
    json.dump(listing_events, f, ensure_ascii=False, indent=2)

with open(OUT_STOCKS_PATH, 'w', encoding='utf-8') as f:
    json.dump(historical_stocks, f, ensure_ascii=False, indent=2)

print(f"Generated {len(listing_events)} listing events and {len(historical_stocks)} historical stock definitions successfully!")
